---
- hosts: localhost
  gather_facts: false
  collections:
    - servicenow.itsm

  vars:
   SN_Username:
   SN_Password:
   SN_Host:

  tasks:
   - name: Create incident
     servicenow.itsm.incident:
      instance:
       host: "{{ SN_HOST }}"
       username: "{{ SN_USERNAME }}"
       password: "{{ SN_PASSWORD }}"
      state: new
      short_description: "New user account created in Active Directory"
      description: |-
       Details: {{ ansible_eda.body.message | default("") }}
       Event-ID: {{ ansible_eda.event.code | default("") }}
       Event-Type: {{ ansible_eda.body.action | default("") }}
      impact: 2  # Change this as needed
      urgency: 2  # Change this as needed
      register: incident_result
