---
- hosts: localhost
  gather_facts: false
  collections:
    - servicenow.itsm

  vars:
   SN_USERNAME:
   SN_PASSWORD:
   SN_HOST:

  tasks:
   - name: Create incident
     servicenow.itsm.incident:
      instance:
       host: "{{ SN_HOST }}"
       username: "{{ SN_USERNAME }}"
       password: "{{ SN_PASSWORD }}"
      state: new
      short_description: {{ ansible_eda.event.body.event.action }}
      description: |-
       Details: {{ ansible_eda.event.body.message | default("") }}
       Event-ID: {{ ansible_eda.event.body.winlog.event-id | default("") }}
       Event-Status: {{ ansible_eda.body.event.outcome | default("") }}
      impact: 2  # Change this as needed
      urgency: 2  # Change this as needed
    #register: incident_result
